truncate table public.recipe_steps restart identity cascade;
truncate table public.recipe_ingredients restart identity cascade;
truncate table public.recipes restart identity cascade;
truncate table public.ingredients restart identity cascade;

insert into public.ingredients (name, category, sort_order, image_url) values
  ('Wortel', 'Sayur', 1, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/wortel.jpg'),
  ('Tempe', 'Protein', 2, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/tempe.jpg'),
  ('Telur', 'Protein', 3, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/telur.jpg'),
  ('Sawi', 'Sayur', 4, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/sawi.jpg'),
  ('Minyak Goreng', 'Bahan Dasar', 5, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/minyak_goreng.jpg'),
  ('Nasi', 'Karbohidrat', 6, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/nasi.jpg'),
  ('Kentang', 'Carb', 7, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/kentang.jpg'),
  ('Ayam', 'Protein', 8, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/ayam.jpg'),
  ('Tahu', 'Sayur/Bumbu', 9, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/tahu.jpg'),
  ('Brokoli', 'Vegetable', 10, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/brokoli.jpg'),
  ('Kol', 'Sayur', 11, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/kol.jpg'),
  ('Mie', 'Karbohidrat', 12, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/mie.jpg'),
  ('Kecap', 'Bumbu', 13, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/kecap.jpg'),
  ('Garam', 'Bumbu', 14, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/garam.jpg'),
  ('Cabai', 'Sayur/Bumbu', 15, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/cabai.jpg'),
  ('Bawang Putih', 'Bumbu', 16, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/bawang_putih.jpg'),
  ('Bawang Merah', 'Bumbu', 17, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/bawang_merah.jpg'),
  ('Bakso', 'Protein', 18, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/bakso.jpg'),
  ('Daun Bawang', 'Sayur', 19, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/daun_bawang.jpg'),
  ('Pokcoy', 'Sayur', 20, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/pokcoy.jpg'),
  ('Kembang Kol', 'Sayur', 21, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/kembang_kol.jpg'),
  ('Margarin', 'Bahan Dasar', 22, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/margarin.jpg'),
  ('Air', 'Bahan Dasar', 23, null),
  ('Bawang Bombay', 'Bumbu', 24, 'https://nvbaxhlexcfaahmzeauq.supabase.co/storage/v1/object/public/ingredient-images/ingredients/bawang_bombay.jpg'),
  ('Saus Tiram', 'Bumbu', 25, null),
  ('Kecap Ikan', 'Bumbu', 26, null),
  ('Minyak Wijen', 'Bumbu', 27, null),
  ('Kaldu Bubuk', 'Bumbu', 28, null),
  ('Gula', 'Bumbu', 29, null),
  ('Lada Bubuk', 'Bumbu', 30, null),
  ('Tepung Maizena', 'Bahan Dasar', 31, null),
  ('Labu Siam', 'Sayur', 32, null),
  ('Jagung', 'Sayur', 33, null),
  ('Kacang Panjang', 'Sayur', 34, null),
  ('Daun Melinjo', 'Sayur', 35, null),
  ('Buah Melinjo', 'Sayur', 36, null),
  ('Asam Jawa', 'Bumbu', 37, null),
  ('Kemiri', 'Bumbu', 38, null),
  ('Terasi', 'Bumbu', 39, null),
  ('Daun Salam', 'Bumbu', 40, null),
  ('Lengkuas', 'Bumbu', 41, null),
  ('Serai', 'Bumbu', 42, null),
  ('Jahe', 'Bumbu', 43, null),
  ('Kunyit', 'Bumbu', 44, null);

insert into public.recipes (name, description, image_url, default_serving, cooking_time) values
  ('Nasi Goreng Telur', 'Nasi goreng gurih dengan telur dan bumbu sederhana.', 'https://loremflickr.com/980/654/rice', 2, 20),
  ('Telur Dadar Cabai', 'Telur dadar pedas praktis untuk lauk cepat.', 'https://loremflickr.com/980/654/egg', 2, 15),
  ('Tahu Goreng Bumbu', 'Tahu goreng renyah dengan bumbu bawang dan kecap.', 'https://loremflickr.com/980/654/tofu', 2, 18),
  ('Mie Goreng Sayur', 'Mie goreng sederhana dengan sayur segar.', 'https://loremflickr.com/980/654/noodle', 2, 20),
  ('Sup Ayam Wortel', 'Sup hangat dengan ayam, wortel, dan kaldu ringan.', 'https://loremflickr.com/980/654/chicken', 3, 35),
  ('Tempe Orek', 'Tempe manis gurih dengan kecap dan bawang.', 'https://loremflickr.com/980/654/food', 3, 20),
  ('Tumis Sawi Bakso', 'Tumis sawi praktis dengan bakso dan bawang.', 'https://loremflickr.com/980/654/vegetable', 2, 18),
  ('Perkedel Kentang', 'Perkedel kentang lembut untuk lauk pendamping.', 'https://loremflickr.com/980/654/potato', 3, 30),
  ('Capcay Bakso Saus Gurih', 'Menu rumahan rasa resto rasa Chinese food dengan sayur crunchy, kuah gurih kental, dan aroma bawang putih minyak wijen.', 'https://loremflickr.com/980/654/capcay', 3, 25),
  ('Sayur Asam Sunda', 'Sayur asam khas Sunda dengan kuah segar yang asam gurih, melinjo, jagung manis, dan labu siam.', 'https://loremflickr.com/980/654/soup', 4, 30),
  ('Ayam Bakar Bumbu Meresap', 'Ayam bakar yang dagingnya super juicy dengan bumbu yang meresap sampai ke tulang.', 'https://loremflickr.com/980/654/chicken', 4, 45);

insert into public.recipe_ingredients (recipe_id, ingredient_id, amount, unit, is_required) values
  ((select id from public.recipes where name = 'Nasi Goreng Telur'), (select id from public.ingredients where name = 'Nasi'), 2, 'piring', true),
  ((select id from public.recipes where name = 'Nasi Goreng Telur'), (select id from public.ingredients where name = 'Telur'), 2, 'butir', true),
  ((select id from public.recipes where name = 'Nasi Goreng Telur'), (select id from public.ingredients where name = 'Bawang Merah'), 3, 'siung', true),
  ((select id from public.recipes where name = 'Nasi Goreng Telur'), (select id from public.ingredients where name = 'Bawang Putih'), 2, 'siung', false),
  ((select id from public.recipes where name = 'Nasi Goreng Telur'), (select id from public.ingredients where name = 'Cabai'), 2, 'buah', false),
  ((select id from public.recipes where name = 'Nasi Goreng Telur'), (select id from public.ingredients where name = 'Kecap'), 2, 'sdm', false),
  ((select id from public.recipes where name = 'Nasi Goreng Telur'), (select id from public.ingredients where name = 'Garam'), 0.5, 'sdt', true),
  ((select id from public.recipes where name = 'Nasi Goreng Telur'), (select id from public.ingredients where name = 'Minyak Goreng'), 2, 'sdm', true),

  ((select id from public.recipes where name = 'Telur Dadar Cabai'), (select id from public.ingredients where name = 'Telur'), 3, 'butir', true),
  ((select id from public.recipes where name = 'Telur Dadar Cabai'), (select id from public.ingredients where name = 'Cabai'), 3, 'buah', false),
  ((select id from public.recipes where name = 'Telur Dadar Cabai'), (select id from public.ingredients where name = 'Bawang Merah'), 2, 'siung', true),
  ((select id from public.recipes where name = 'Telur Dadar Cabai'), (select id from public.ingredients where name = 'Garam'), 0.5, 'sdt', true),
  ((select id from public.recipes where name = 'Telur Dadar Cabai'), (select id from public.ingredients where name = 'Minyak Goreng'), 2, 'sdm', true),

  ((select id from public.recipes where name = 'Tahu Goreng Bumbu'), (select id from public.ingredients where name = 'Tahu'), 4, 'potong', true),
  ((select id from public.recipes where name = 'Tahu Goreng Bumbu'), (select id from public.ingredients where name = 'Bawang Putih'), 2, 'siung', true),
  ((select id from public.recipes where name = 'Tahu Goreng Bumbu'), (select id from public.ingredients where name = 'Garam'), 0.5, 'sdt', true),
  ((select id from public.recipes where name = 'Tahu Goreng Bumbu'), (select id from public.ingredients where name = 'Kecap'), 1, 'sdm', false),
  ((select id from public.recipes where name = 'Tahu Goreng Bumbu'), (select id from public.ingredients where name = 'Minyak Goreng'), 3, 'sdm', true),

  ((select id from public.recipes where name = 'Mie Goreng Sayur'), (select id from public.ingredients where name = 'Mie'), 2, 'bungkus', true),
  ((select id from public.recipes where name = 'Mie Goreng Sayur'), (select id from public.ingredients where name = 'Kol'), 100, 'gram', false),
  ((select id from public.recipes where name = 'Mie Goreng Sayur'), (select id from public.ingredients where name = 'Sawi'), 100, 'gram', false),
  ((select id from public.recipes where name = 'Mie Goreng Sayur'), (select id from public.ingredients where name = 'Wortel'), 1, 'buah', false),
  ((select id from public.recipes where name = 'Mie Goreng Sayur'), (select id from public.ingredients where name = 'Bawang Putih'), 2, 'siung', true),
  ((select id from public.recipes where name = 'Mie Goreng Sayur'), (select id from public.ingredients where name = 'Kecap'), 2, 'sdm', false),
  ((select id from public.recipes where name = 'Mie Goreng Sayur'), (select id from public.ingredients where name = 'Minyak Goreng'), 2, 'sdm', true),

  ((select id from public.recipes where name = 'Sup Ayam Wortel'), (select id from public.ingredients where name = 'Ayam'), 250, 'gram', true),
  ((select id from public.recipes where name = 'Sup Ayam Wortel'), (select id from public.ingredients where name = 'Wortel'), 2, 'buah', true),
  ((select id from public.recipes where name = 'Sup Ayam Wortel'), (select id from public.ingredients where name = 'Kentang'), 2, 'buah', false),
  ((select id from public.recipes where name = 'Sup Ayam Wortel'), (select id from public.ingredients where name = 'Bawang Merah'), 3, 'siung', true),
  ((select id from public.recipes where name = 'Sup Ayam Wortel'), (select id from public.ingredients where name = 'Bawang Putih'), 2, 'siung', true),
  ((select id from public.recipes where name = 'Sup Ayam Wortel'), (select id from public.ingredients where name = 'Daun Bawang'), 1, 'batang', false),
  ((select id from public.recipes where name = 'Sup Ayam Wortel'), (select id from public.ingredients where name = 'Garam'), 1, 'sdt', true),

  ((select id from public.recipes where name = 'Tempe Orek'), (select id from public.ingredients where name = 'Tempe'), 200, 'gram', true),
  ((select id from public.recipes where name = 'Tempe Orek'), (select id from public.ingredients where name = 'Bawang Merah'), 3, 'siung', true),
  ((select id from public.recipes where name = 'Tempe Orek'), (select id from public.ingredients where name = 'Bawang Putih'), 2, 'siung', true),
  ((select id from public.recipes where name = 'Tempe Orek'), (select id from public.ingredients where name = 'Cabai'), 2, 'buah', false),
  ((select id from public.recipes where name = 'Tempe Orek'), (select id from public.ingredients where name = 'Kecap'), 2, 'sdm', false),
  ((select id from public.recipes where name = 'Tempe Orek'), (select id from public.ingredients where name = 'Minyak Goreng'), 2, 'sdm', true),

  ((select id from public.recipes where name = 'Tumis Sawi Bakso'), (select id from public.ingredients where name = 'Sawi'), 150, 'gram', true),
  ((select id from public.recipes where name = 'Tumis Sawi Bakso'), (select id from public.ingredients where name = 'Bakso'), 6, 'butir', true),
  ((select id from public.recipes where name = 'Tumis Sawi Bakso'), (select id from public.ingredients where name = 'Bawang Putih'), 2, 'siung', true),
  ((select id from public.recipes where name = 'Tumis Sawi Bakso'), (select id from public.ingredients where name = 'Cabai'), 2, 'buah', false),
  ((select id from public.recipes where name = 'Tumis Sawi Bakso'), (select id from public.ingredients where name = 'Garam'), 0.5, 'sdt', true),
  ((select id from public.recipes where name = 'Tumis Sawi Bakso'), (select id from public.ingredients where name = 'Minyak Goreng'), 2, 'sdm', true),

  ((select id from public.recipes where name = 'Perkedel Kentang'), (select id from public.ingredients where name = 'Kentang'), 3, 'buah', true),
  ((select id from public.recipes where name = 'Perkedel Kentang'), (select id from public.ingredients where name = 'Telur'), 1, 'butir', true),
  ((select id from public.recipes where name = 'Perkedel Kentang'), (select id from public.ingredients where name = 'Bawang Putih'), 2, 'siung', true),
  ((select id from public.recipes where name = 'Perkedel Kentang'), (select id from public.ingredients where name = 'Daun Bawang'), 1, 'batang', false),
  ((select id from public.recipes where name = 'Perkedel Kentang'), (select id from public.ingredients where name = 'Garam'), 0.5, 'sdt', true),
  ((select id from public.recipes where name = 'Perkedel Kentang'), (select id from public.ingredients where name = 'Minyak Goreng'), 3, 'sdm', true),

  -- Capcay Bakso Saus Gurih
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Wortel'), 1, 'buah', true),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Pokcoy'), 3, 'lembar', true),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Kembang Kol'), 1, 'bonggol', true),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Bakso'), 10, 'buah', true),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Telur'), 1, 'butir', true),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Margarin'), 1, 'sdm', false),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Air'), 250, 'ml', false),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Bawang Putih'), 4, 'siung', false),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Bawang Bombay'), 0.5, 'buah', false),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Saus Tiram'), 2, 'sdm', false),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Kecap Ikan'), 1, 'sdm', false),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Minyak Wijen'), 1, 'sdm', false),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Kaldu Bubuk'), 1, 'sdm', false),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Gula'), 0.25, 'sdt', false),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Garam'), 0.5, 'sdt', false),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Lada Bubuk'), 0.5, 'sdt', false),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), (select id from public.ingredients where name = 'Tepung Maizena'), 1, 'sdm', false),
  
  -- Sayur Asam Sunda
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Labu Siam'), 1, 'buah', true),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Jagung'), 2, 'buah', true),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Kacang Panjang'), 6, 'lonjor', true),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Daun Melinjo'), 2, 'ikat', true),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Buah Melinjo'), 100, 'gram', true),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Asam Jawa'), 1, 'sejempol', true),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Air'), 600, 'ml', false),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Bawang Merah'), 7, 'butir', false),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Bawang Putih'), 3, 'siung', false),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Kemiri'), 4, 'butir', false),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Cabai'), 4, 'buah', false),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Terasi'), 0.5, 'sdt', false),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Daun Salam'), 2, 'lembar', false),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Lengkuas'), 1, 'ruas', false),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Serai'), 1, 'batang', false),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Gula'), 1, 'sdt', false),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Garam'), 0.5, 'sdt', false),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), (select id from public.ingredients where name = 'Kaldu Bubuk'), 0.5, 'sdt', false),

  -- Ayam Bakar Bumbu Meresap
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), (select id from public.ingredients where name = 'Ayam'), 1, 'ekor', true),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), (select id from public.ingredients where name = 'Bawang Merah'), 8, 'siung', false),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), (select id from public.ingredients where name = 'Bawang Putih'), 5, 'siung', false),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), (select id from public.ingredients where name = 'Kemiri'), 4, 'butir', false),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), (select id from public.ingredients where name = 'Cabai'), 3, 'buah', false),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), (select id from public.ingredients where name = 'Jahe'), 2, 'cm', false),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), (select id from public.ingredients where name = 'Kunyit'), 2, 'cm', false),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), (select id from public.ingredients where name = 'Daun Salam'), 2, 'lembar', false),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), (select id from public.ingredients where name = 'Serai'), 1, 'batang', false),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), (select id from public.ingredients where name = 'Air'), 300, 'ml', false),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), (select id from public.ingredients where name = 'Kecap'), 3, 'sdm', false),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), (select id from public.ingredients where name = 'Garam'), 1, 'sdt', false),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), (select id from public.ingredients where name = 'Kaldu Bubuk'), 1, 'sdt', false),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), (select id from public.ingredients where name = 'Gula'), 1, 'sdt', false),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), (select id from public.ingredients where name = 'Margarin'), 1, 'sdm', false);

insert into public.recipe_steps (recipe_id, step_number, instruction) values
  ((select id from public.recipes where name = 'Nasi Goreng Telur'), 1, 'Panaskan minyak, lalu tumis bawang merah, bawang putih, dan cabai sampai harum.'),
  ((select id from public.recipes where name = 'Nasi Goreng Telur'), 2, 'Masukkan telur dan orak-arik hingga matang.'),
  ((select id from public.recipes where name = 'Nasi Goreng Telur'), 3, 'Tambahkan nasi, kecap, dan garam, lalu aduk hingga tercampur rata.'),
  ((select id from public.recipes where name = 'Nasi Goreng Telur'), 4, 'Masak hingga nasi panas merata, kemudian sajikan.'),

  ((select id from public.recipes where name = 'Telur Dadar Cabai'), 1, 'Iris cabai dan bawang merah, lalu campur bersama telur dan garam.'),
  ((select id from public.recipes where name = 'Telur Dadar Cabai'), 2, 'Panaskan minyak di wajan datar.'),
  ((select id from public.recipes where name = 'Telur Dadar Cabai'), 3, 'Tuang adonan telur dan masak hingga kedua sisi matang.'),

  ((select id from public.recipes where name = 'Tahu Goreng Bumbu'), 1, 'Haluskan bawang putih and garam, lalu balurkan ke potongan tahu.'),
  ((select id from public.recipes where name = 'Tahu Goreng Bumbu'), 2, 'Panaskan minyak, goreng tahu hingga keemasan.'),
  ((select id from public.recipes where name = 'Tahu Goreng Bumbu'), 3, 'Angkat dan sajikan dengan kecap sebagai pelengkap.'),

  ((select id from public.recipes where name = 'Mie Goreng Sayur'), 1, 'Rebus mie hingga setengah matang lalu tiriskan.'),
  ((select id from public.recipes where name = 'Mie Goreng Sayur'), 2, 'Tumis bawang putih sampai harum, lalu masukkan wortel, kol, dan sawi.'),
  ((select id from public.recipes where name = 'Mie Goreng Sayur'), 3, 'Masukkan mie dan kecap, lalu aduk hingga bumbu rata.'),
  ((select id from public.recipes where name = 'Mie Goreng Sayur'), 4, 'Masak sebentar sampai sayur layu dan mie siap disajikan.'),

  ((select id from public.recipes where name = 'Sup Ayam Wortel'), 1, 'Tumis bawang merah dan bawang putih hingga harum.'),
  ((select id from public.recipes where name = 'Sup Ayam Wortel'), 2, 'Masukkan ayam, aduk sampai berubah warna.'),
  ((select id from public.recipes where name = 'Sup Ayam Wortel'), 3, 'Tambahkan air, wortel, kentang, dan garam, lalu masak hingga empuk.'),
  ((select id from public.recipes where name = 'Sup Ayam Wortel'), 4, 'Masukkan daun bawang sesaat sebelum diangkat.'),

  ((select id from public.recipes where name = 'Tempe Orek'), 1, 'Potong tempe kecil-kecil lalu goreng setengah kering.'),
  ((select id from public.recipes where name = 'Tempe Orek'), 2, 'Tumis bawang merah, bawang putih, dan cabai sampai harum.'),
  ((select id from public.recipes where name = 'Tempe Orek'), 3, 'Masukkan tempe dan kecap, aduk hingga meresap.'),

  ((select id from public.recipes where name = 'Tumis Sawi Bakso'), 1, 'Iris bakso dan potong sawi sesuai selera.'),
  ((select id from public.recipes where name = 'Tumis Sawi Bakso'), 2, 'Tumis bawang putih dan cabai sampai harum.'),
  ((select id from public.recipes where name = 'Tumis Sawi Bakso'), 3, 'Masukkan bakso, lalu sawi, garam, and sedikit air.'),
  ((select id from public.recipes where name = 'Tumis Sawi Bakso'), 4, 'Masak hingga sawi layu dan bakso panas merata.'),

  ((select id from public.recipes where name = 'Perkedel Kentang'), 1, 'Kupas kentang, potong-potong, lalu goreng atau rebus hingga empuk.'),
  ((select id from public.recipes where name = 'Perkedel Kentang'), 2, 'Haluskan kentang dan campur dengan bawang putih, daun bawang, garam, dan telur.'),
  ((select id from public.recipes where name = 'Perkedel Kentang'), 3, 'Bentuk bulat pipih sesuai selera.'),
  ((select id from public.recipes where name = 'Perkedel Kentang'), 4, 'Goreng dalam minyak panas hingga kedua sisi kecokelatan.'),

  -- Capcay Bakso Saus Gurih
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), 1, 'Panaskan sedikit minyak dan margarin dalam wajan.'),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), 2, 'Tuang telur lalu buat orak-arik hingga matang. Sisihkan di pinggir wajan 🥚'),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), 3, 'Masukkan bawang putih dan bawang bombay, tumis hingga harum dan layu 🤤'),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), 4, 'Masukkan bakso lalu tumis 2–3 menit hingga setengah matang 🍡'),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), 5, 'Tambahkan ini https://s.shopee.co.id/6AiklMzaDq ya, kemudian saus tiram, minyak wijen, gula, dan sedikit kaldu bubuk. Aduk rata ✨'),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), 6, 'Masukkan wortel lalu tumis hingga mulai empuk 🥕'),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), 7, 'Masukkan kembang kol dan pokcoy 🥬🥦'),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), 8, 'Tuang air lalu masak hingga mendidih.'),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), 9, 'Tambahkan garam, lada bubuk, dan sisa kaldu ayam bubuk.'),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), 10, 'Larutkan pengental ini https://s.shopee.co.id/8ATp98XsVR dengan air lalu tuang perlahan sambil diaduk cepat.'),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), 11, 'Masak hingga kuah mengental dan semua sayuran matang.'),
  ((select id from public.recipes where name = 'Capcay Bakso Saus Gurih'), 12, 'Koreksi rasa lalu angkat 😩❤️'),

  -- Sayur Asam Sunda
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), 1, 'Didihkan air dalam panci.'),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), 2, 'Masukkan jagung dan buah melinjo lalu rebus hingga mulai empuk 🌽'),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), 3, 'Masukkan bumbu halus, daun salam, lengkuas, serai, dan jangan lupa tambahkan ini https://s.shopee.co.id/4qDMn1nQTi ya 🍲'),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), 4, 'Aduk rata lalu masukkan potongan labu siam.'),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), 5, 'Masak hingga mendidih dan sayuran mulai matang 🤤'),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), 6, 'Tambahkan gula pasir, garam, dan kaldu bubuk.'),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), 7, 'Aduk lalu koreksi rasa.'),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), 8, 'Masukkan kacang panjang dan daun melinjo 🫛🌿'),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), 9, 'Masak sebentar hingga daun melinjo layu tetapi masih hijau segar.'),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), 10, 'Cicipi kuahnya, pastikan rasa asam segarnya terasa pas. Jika kurang asam, tambahkan sedikit air asam jawa lagi 🍋✨'),
  ((select id from public.recipes where name = 'Sayur Asam Sunda'), 11, 'Angkat dan sajikan selagi hangat 😩❤️'),

  -- Ayam Bakar Bumbu Meresap
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), 1, 'Haluskan bawang merah, bawang putih, kemiri, cabai merah, jahe, dan kunyit 🌶️'),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), 2, 'Tumis bumbu halus sampai harum dan matang 😍'),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), 3, 'Masukkan daun salam dan serai, aduk sebentar 🌿'),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), 4, 'Masukkan ayam, lalu aduk sampai terbalut bumbu 🍗'),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), 5, 'Tambahkan air, garam, kaldu bubuk, gula, dan kecap manis 🥢'),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), 6, 'Ungkep dengan api kecil sampai ayam matang dan air menyusut 🔥'),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), 7, 'Campurkan sedikit sisa bumbu ungkep dengan kecap manis dan mentega 🧈'),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), 8, 'Oleskan ke seluruh permukaan ayam ✨'),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), 9, 'Bakar atau panggang sampai permukaan ayam kecokelatan dan mengilap 🤤🔥 karena aku gak pakai arang, jadi aku pakai ini ya bund https://s.shopee.co.id/60P9MpqEcE 🤭'),
  ((select id from public.recipes where name = 'Ayam Bakar Bumbu Meresap'), 10, 'Sajikan dengan nasi hangat, sambal, dan lalapan 🍚🌶️');
