create table if not exists public.ingredients (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  image_url text,
  default_serving int not null default 1,
  cooking_time int,
  created_at timestamp with time zone default now()
);

create table if not exists public.recipe_ingredients (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  ingredient_id bigint not null references public.ingredients(id) on delete cascade,
  amount numeric not null,
  unit text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.recipe_steps (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  step_number int not null,
  instruction text not null,
  created_at timestamp with time zone default now()
);

create index if not exists ingredients_category_idx
  on public.ingredients(category);

create index if not exists recipe_ingredients_recipe_id_idx
  on public.recipe_ingredients(recipe_id);

create index if not exists recipe_steps_recipe_id_idx
  on public.recipe_steps(recipe_id);

alter table public.ingredients enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_ingredients enable row level security;
alter table public.recipe_steps enable row level security;

drop policy if exists "Allow public read ingredients" on public.ingredients;
create policy "Allow public read ingredients"
on public.ingredients
for select
to anon
using (true);

drop policy if exists "Allow public read recipes" on public.recipes;
create policy "Allow public read recipes"
on public.recipes
for select
to anon
using (true);

drop policy if exists "Allow public read recipe ingredients" on public.recipe_ingredients;
create policy "Allow public read recipe ingredients"
on public.recipe_ingredients
for select
to anon
using (true);

drop policy if exists "Allow public read recipe steps" on public.recipe_steps;
create policy "Allow public read recipe steps"
on public.recipe_steps
for select
to anon
using (true);
