create table if not exists public.ai_generated_recipes (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  cooking_time integer not null default 0 check (cooking_time >= 0),
  servings integer not null default 1 check (servings > 0),
  ingredients_json jsonb not null default '[]'::jsonb,
  steps_json jsonb not null default '[]'::jsonb,
  selected_ingredients_json jsonb not null default '[]'::jsonb,
  selected_ingredients_key text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists ai_generated_recipes_created_at_idx
  on public.ai_generated_recipes (created_at desc);

alter table public.ai_generated_recipes enable row level security;
